meta_product_name: "La beauté autrement"
meta_title: "Salon de beauté à La Méziere - bien être éco-responsable"
meta_description: "Soins du corp et vente de produits en accord avec vos valeurs"
meta_image: "" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards
